# gcloud compute addresses create hispanie-ip --global
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: hispanie-ip
    networking.gke.io/managed-certificates: "app-managed-cert,api-managed-cert"
    kubernetes.io/ingress.class: "gce"
spec:
  ingressClassName: gce
  rules:
    - host: api.hispanie.com
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3201
    - host: app.hispanie.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 8080
